"""Init migration

Revision ID: 0ca0d7c8b0ff
Revises: 
Create Date: 2024-06-19 22:01:37.006465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca0d7c8b0ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.CHAR(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['image_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_hash')

    # ### end Alembic commands ###
