"""Add image hash column to Image table

Revision ID: 7b25ab0dea39
Revises: 0ca0d7c8b0ff
Create Date: 2024-06-19 23:02:31.930522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b25ab0dea39'
down_revision = '0ca0d7c8b0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('image_image_hash_key', type_='unique')
        batch_op.drop_column('image_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.CHAR(length=64), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('image_image_hash_key', ['image_hash'])

    # ### end Alembic commands ###
