"""Add image hash column to Image table

Revision ID: 93d3a4506219
Revises: 7b25ab0dea39
Create Date: 2024-06-19 23:04:09.363293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d3a4506219'
down_revision = '7b25ab0dea39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.CHAR(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['image_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_hash')

    # ### end Alembic commands ###
